// Generated by gencpp from file delivery_topics/MenuSelectorResponse.msg
// DO NOT EDIT!


#ifndef DELIVERY_TOPICS_MESSAGE_MENUSELECTORRESPONSE_H
#define DELIVERY_TOPICS_MESSAGE_MENUSELECTORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_topics
{
template <class ContainerAllocator>
struct MenuSelectorResponse_
{
  typedef MenuSelectorResponse_<ContainerAllocator> Type;

  MenuSelectorResponse_()
    : message()  {
    }
  MenuSelectorResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MenuSelectorResponse_

typedef ::delivery_topics::MenuSelectorResponse_<std::allocator<void> > MenuSelectorResponse;

typedef boost::shared_ptr< ::delivery_topics::MenuSelectorResponse > MenuSelectorResponsePtr;
typedef boost::shared_ptr< ::delivery_topics::MenuSelectorResponse const> MenuSelectorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator1> & lhs, const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator1> & lhs, const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_topics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_topics/MenuSelectorResponse";
  }

  static const char* value(const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"\n"
;
  }

  static const char* value(const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MenuSelectorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_topics::MenuSelectorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_topics::MenuSelectorResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_TOPICS_MESSAGE_MENUSELECTORRESPONSE_H
